server:
  port: 9094

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfile
      username: bilgeUser
      password: bilgeUser

logging:
  level:
    org.springframework:
    com.CK: info


#userservice:
#  deger1: "1.Deger"
#  deger2: "2.Deger"
#  listem:
#    bir: "bu ilk deger"
#    iki: "bu ikinci deger"
#
#ahmetamcanasilsin:
#  iyiyim: "sen nasilsin?"